# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Ddosify

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Ddosify
      run: go install -v go.ddosify.com/ddosify@latest

    - name: Run Ddosify!
      run: ddosify -t ${{ secrets.URL }} -d 1000 -n 100000
